# Site settings
title: Magic Frying Pan
email: magicfryingpan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Magic Frying Pan is a community where games are analyzed, reviewed, and reflected upon.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://magicfryingpan.com" # the base hostname & protocol for your site
permalink: none
sass:
    sass_dir: _sass
    style: compressed
twitter_username: magicfryingpan
github_username:  magicfryingpan

# Build settings
markdown: kramdown
